[node]
key = "your_openai_api_key"
url = "https://api.openai.com/v1"
model="gpt-3.5-turbo"

[status-node]
key = "your_openai_api_key"
url = "https://api.openai.com/v1"
model="gpt-3.5-turbo"

[reactor]
key = "your_openai_api_key"
url = "https://api.openai.com/v1"
model="gpt-3.5-turbo"

[router]
key = "your_openai_api_key"
url = "https://api.openai.com/v1"
model="gpt-3.5-turbo"


[file]
key = "your_openai_api_key"
url = "https://api.openai.com/v1"
model="gpt-3.5-turbo"

[web-search]
key = "your_openai_api_key"
url = "https://api.openai.com/v1"
model="gpt-3.5-turbo"